services:
  nginx:
    image: nginx:latest
    container_name: nginxserver
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf_d:/etc/nginx/conf.d
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 1; done'"
    networks:
      - app-network

networks:
  app-network:
    external: true