services:
  app-blue:
    image: sj0320/planu-app:latest
    container_name: planu-app-green
    ports:
      - "8082:8080"
    env_file: .env
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    networks:
      - app-network
    depends_on:
      - db
      - redis

networks:
  app-network:
    external: true