package com.planu.group_meeting.entity.common;

public enum EventType {
    FRIEND_REQUEST,
    FRIEND_ACCEPT,
    COMMENT,
    SCHEDULE_REMINDER,
    GROUP_DELETE,
    GROUP_INVITE,
    GROUP_ACCEPT,
    GROUP_EXPEL,
    GROUP_SCHEDULE_CREATE,
    GROUP_SCHEDULE_DELETE,
    BIRTHDAY,
    GROUP_INVITATION_CANCELLED,
    GROUP_MEMBER_LEFT,
    DUMMY
}
