name: Deploy to EC2 with Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Check out the repository
        uses: actions/checkout@v2

      # 2. JDK 설치 및 Gradle 빌드
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build .jar file with Gradle
        run: ./gradlew clean bootJar

      # 3. Docker 로그인
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4. Docker 이미지 빌드 및 푸시
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/planu-backend:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/planu-backend:latest

      # 5. SSH로 EC2 서버에 접속하여 Docker 컨테이너 실행
      - name: Deploy on EC2
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.AWS_EC2_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/planu-backend:latest
            docker stop planu-backend || true
            docker rm planu-backend || true
            docker run -d --name planu-backend -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/planu-backend:latest
