name: Deploy to EC2

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Check out the repository
        uses: actions/checkout@v2

      # 2. gradlew에 실행 권한 추가
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # 3. JAR 파일 생성
      - name: Build .jar file with Gradle
        run: ./gradlew clean bootJar

      # 4. SSH 설정
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      # 5. 파일을 EC2로 복사
      - name: Copy files to EC2
        run: |
          scp -o StrictHostKeyChecking=no -r ./* ubuntu@${{ secrets.AWS_EC2_IP }}:/home/ubuntu/projects/planu-backend

      # 6. EC2에서 Docker Compose 실행
      - name: Run Docker Compose on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.AWS_EC2_IP }} << 'EOF'
            cd /home/ubuntu/projects/planu-backend
            echo "Copying environment variables..."
            touch .env
            export SPRING_DATASOURCE_URL=${{ secrets.SPRING_DATASOURCE_URL }}
            export SPRING_DATASOURCE_USERNAME=${{ secrets.SPRING_DATASOURCE_USERNAME }}
            export SPRING_DATASOURCE_PASSWORD=${{ secrets.SPRING_DATASOURCE_PASSWORD }}
            export REDIS_HOST=${{ secrets.REDIS_HOST }}
            export REDIS_PORT=${{ secrets.REDIS_PORT }}
            export MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}
            export MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}
            docker-compose down
            docker-compose up -d --build
          EOF
